// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
  
using System.Reflection;

[assembly: AssemblyTitle("HawDict")]
[assembly: AssemblyDescription("Creates offline Hawaiian dictionaries.")]
[assembly: AssemblyCopyright("Copyright © 2018 Jon Thysell")]

[assembly: AssemblyCompany("Jon Thysell")]
[assembly: AssemblyProduct("HawDict")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]

[assembly: AssemblyVersion("0.9.0.0")]
[assembly: AssemblyFileVersion("0.9.0.0")]
